### ISSUE TITLE
Prevent Default & Buttons

### ISSUE THREAD

**Issue by Iheartweb** [Droppe/Lu#248]
Should buttons prevent default by default? Should we intelligently prevent default based on markup?

**Comment by Jimgskoop** [comment]
Yes!  There are many cases on Davinci where the page is jumping around to relative links from anchors (e.g. Accordion) because we're not preventing the default behavior.  I put a temporary patch in place in the Davinci code, but IMHO it should happen within the Lu framework (or in Abstract, or within Button itself).

**Comment by drewlee** [comment]
Agreed, we definitely need a way to prevent default, but there needs to be a manner of specifying a link to follow a url if needed.

**Comment by Iheartweb** [comment]
Should `role="button"` be the equivalent of `{ preventDefault: true }`?

**Comment by Iheartweb** [comment]
Alternatively, as a default `{ preventDefault: true }` and in the cases where you want the hash to be updated or the button to resolve to another url, you'd have to set it to false.

**Comment by Jimgskoop** [comment]
I like this idea.

-Jim G

On Oct 2, 2012, at 8:41 PM, Robert Martone wrote:

Alternatively, as a default { preventDefault: true } and in the cases where you want the hash to be updated or the button to resolve to another url, you'd have to set it to false.

**Comment by Iheartweb** [comment]
default prevented by default!
