### ISSUE TITLE
Alert Control

### ISSUE THREAD

**Issue by Jimgskoop** [Droppe/Lu#54]
build an alert control; also merge together Container, Loader, and Tip

JS Code
HTML examples
Functional completeness
Documentation + Example in Primer
Unit testing (work with Kiro)

**Comment by Iheartweb** [comment]
More thoughts from our conversations about the use of container.

In this case there would be no alert control. And Container would listen for a 'close' event.

```
<div data-lu="Container" class="warning-alert">
  <p>Warning Message</p>
  <button type="button" data-lu="Close:Button">Close</button>
</div>
```

In this case Alert would extend or encapsulate Container, and either Alert or Container could listen for the close event. Note: I like using the explicit 'Alert' vs the Generic Container.

```
<div data-lu="Alert" class="warning-alert">
  <p>Warning Message</p>
  <button type="button" data-lu="Close:Button">Close</button>
</div>
```

In other cases like Dialog you might have this.

```
<div data-lu="Dialog" class="warning-alert">
  <h2>Title</h2>
  <p>Dialog Content</p>
  <button type="button" data-lu="Close:Button">Close</button>
</div>
```

In this case Dialog could extend or encapsulate Container as well, and likewise either Dialog or Container could listen for the close event.

Although the event listener may be abstracted into Container, there will most likely be behavioral differences between Dialog and Alert. Alert will probably just hide itself. Dialog may clean up other elements like a shim or a mask, before hiding itself. 
Because of that an event abstracted in container would have to call methods on dialog and alert.

Assuming Dialog and Alert extend Container.

```
Container.on( 'close', function( event, $subject ){
  Container.close();
} )
```

Where Dialog would have:

```
Dialog.close = function() {
  //cleanup the dom
  //hide the Dialog
}
```

For this to work Alert and Container would have to have the same interface. This is ok here, but as we get to other controls verbs like hide, or collapse make more sense than close.

In Alert, extension works well. Container.close and Alert.close do the same thing. But in Dialog, you'd have to overwrite the close method, so setting up dialog as a manager that encapsulates Container makes more sense. I'd rather see this, then have to overwrite the method:

```
Dialog.close = function() {
  //Do all the dialogy stuff here
  Container.close();
}
```

Likewise Tip will also have behavior other than just hiding itself.

```
Tip.close = function() {
  //Detach event listeners;
  Container.close();
}
```

And Accordion or Tabs might:

```
Accordion.collapse = function() {
  getActiveContainer.close();//something like that
}
```

So, why event bother with Container? --> We need a common way to load and unload content.

##Encapsulation vs Extension?

Both! - Alerts should and Reveal should extend. Dialog, Tip and Controls with multiple Containers should manage container.

**Comment by Iheartweb** [comment]
Per discussion, this should be developed for the LinkedIn pattern by the DaVinci team.
